type: "energy_controller/MyEnergyShapingPositionController"
robot_model_chains: ["right_wrist"]
dt: 0.01

joints:
    - jright_shoulder_rotz
    - jright_shoulder_roty
    - jright_shoulder_rotx
    - jright_forearm_rotz
    - jright_forearm_roty
    - jright_wrist_rotz
    - jright_wrist_rotx

#robot_model_chains: ["gripper_left_link"]
#dt: 0.01

#    - torso_lift_joint
#    - arm_left_1_joint
#    - arm_left_2_joint
#    - arm_left_3_joint
#    - arm_left_4_joint
#    - arm_left_5_joint
#    - arm_left_6_joint
#    - arm_left_7_joint
